-- MySQL Script generated by MySQL Workbench
-- Sat May  3 19:01:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema asturias
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `asturias` ;

-- -----------------------------------------------------
-- Schema asturias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asturias` DEFAULT CHARACTER SET utf8 ;
USE `asturias` ;

-- -----------------------------------------------------
-- Table `asturias`.`council`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`council` ;

CREATE TABLE IF NOT EXISTS `asturias`.`council` (
  `council_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `zone` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`council_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`area` ;

CREATE TABLE IF NOT EXISTS `asturias`.`area` (
  `area_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `image` VARCHAR(300) NOT NULL,
  `latitude` DECIMAL(10,8) NOT NULL,
  `longitude` DECIMAL(11,8) NOT NULL,
  `drinking_water` TINYINT UNSIGNED NOT NULL,
  `waste_water` TINYINT UNSIGNED NOT NULL,
  `black_water` TINYINT UNSIGNED NOT NULL,
  `places` INT UNSIGNED NULL,
  `access` VARCHAR(300) NULL,
  `type` ENUM("public", "private") NOT NULL DEFAULT 'public',
  `max_stay` VARCHAR(45) NULL,
  `address` VARCHAR(128) NOT NULL,
  `council_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`area_id`),
  UNIQUE INDEX `nombre_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_areas_autocaravanas_concejos_idx` (`council_id` ASC) VISIBLE,
  CONSTRAINT `fk_areas_autocaravanas_concejos`
    FOREIGN KEY (`council_id`)
    REFERENCES `asturias`.`council` (`council_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`route`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`route` ;

CREATE TABLE IF NOT EXISTS `asturias`.`route` (
  `route_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `image` VARCHAR(300) NOT NULL,
  `latitude` DECIMAL(10,8) NOT NULL,
  `longitude` DECIMAL(11,8) NOT NULL,
  `type` ENUM('hiking', 'mountain_bike', 'summit', 'by_car') NOT NULL,
  `information` VARCHAR(600) NOT NULL,
  `web` VARCHAR(300) NULL,
  `distance` INT UNSIGNED NOT NULL,
  `time` VARCHAR(45) NULL,
  `origin_destination` VARCHAR(128) NULL,
  `council_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`route_id`),
  INDEX `fk_rutas_concejos1_idx` (`council_id` ASC) VISIBLE,
  CONSTRAINT `fk_rutas_concejos1`
    FOREIGN KEY (`council_id`)
    REFERENCES `asturias`.`council` (`council_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`preroman_art`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`preroman_art` ;

CREATE TABLE IF NOT EXISTS `asturias`.`preroman_art` (
  `preroman_art_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `image` VARCHAR(300) NOT NULL,
  `latitude` DECIMAL(10,8) NOT NULL,
  `longitude` DECIMAL(11,8) NOT NULL,
  `unesco_heritage` TINYINT NOT NULL DEFAULT 0,
  `information` VARCHAR(300) NULL,
  `web` VARCHAR(128) NULL,
  `address` VARCHAR(128) NULL,
  `council_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`preroman_art_id`),
  INDEX `fk_arte_prerromanico_concejos1_idx` (`council_id` ASC) VISIBLE,
  CONSTRAINT `fk_arte_prerromanico_concejos1`
    FOREIGN KEY (`council_id`)
    REFERENCES `asturias`.`council` (`council_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`beach`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`beach` ;

CREATE TABLE IF NOT EXISTS `asturias`.`beach` (
  `beach_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `image` VARCHAR(300) NOT NULL,
  `latitude` DECIMAL(10,8) NOT NULL,
  `longitude` DECIMAL(11,8) NOT NULL,
  `information` VARCHAR(300) NOT NULL,
  `services` VARCHAR(255) NOT NULL,
  `beach_type` VARCHAR(128) NOT NULL,
  `council_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`beach_id`),
  INDEX `fk_playas_concejos1_idx` (`council_id` ASC) VISIBLE,
  CONSTRAINT `fk_playas_concejos1`
    FOREIGN KEY (`council_id`)
    REFERENCES `asturias`.`council` (`council_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`rock_art`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`rock_art` ;

CREATE TABLE IF NOT EXISTS `asturias`.`rock_art` (
  `rock_art_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `image` VARCHAR(300) NOT NULL,
  `latitude` DECIMAL(10,8) NOT NULL,
  `longitude` DECIMAL(11,8) NOT NULL,
  `period` VARCHAR(45) NOT NULL,
  `information` VARCHAR(300) NOT NULL,
  `web` VARCHAR(128) NULL,
  `council_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`rock_art_id`),
  INDEX `fk_arte_rupestre_concejos1_idx` (`council_id` ASC) VISIBLE,
  CONSTRAINT `fk_arte_rupestre_concejos1`
    FOREIGN KEY (`council_id`)
    REFERENCES `asturias`.`council` (`council_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`museum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`museum` ;

CREATE TABLE IF NOT EXISTS `asturias`.`museum` (
  `museum_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `image` VARCHAR(300) NOT NULL,
  `latitude` DECIMAL(10,8) NOT NULL,
  `longitude` DECIMAL(11,8) NOT NULL,
  `web` VARCHAR(128) NULL,
  `information` VARCHAR(300) NOT NULL,
  `free` TINYINT NOT NULL,
  `council_id` INT UNSIGNED NOT NULL,
  `address` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`museum_id`),
  INDEX `fk_museos_espacios_culturales_concejos1_idx` (`council_id` ASC) VISIBLE,
  CONSTRAINT `fk_museos_espacios_culturales_concejos1`
    FOREIGN KEY (`council_id`)
    REFERENCES `asturias`.`council` (`council_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`user` ;

CREATE TABLE IF NOT EXISTS `asturias`.`user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `role` ENUM('admin', 'user') NOT NULL DEFAULT 'user',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`favourite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`favourite` ;

CREATE TABLE IF NOT EXISTS `asturias`.`favourite` (
  `favourite_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` ENUM('area', 'route', 'beach', 'museum', 'preroman', 'rockArt') NOT NULL,
  `point_id` INT UNSIGNED NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`favourite_id`),
  INDEX `fk_favourites_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_favourites_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `asturias`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`visited`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`visited` ;

CREATE TABLE IF NOT EXISTS `asturias`.`visited` (
  `visited_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` ENUM('area', 'route', 'preroman', 'beach', 'museum', 'rockArt') NOT NULL,
  `point_id` INT UNSIGNED NOT NULL,
  `comments` VARCHAR(400) NULL,
  `visit_date` DATE NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`visited_id`),
  INDEX `fk_visited_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_visited_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `asturias`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
