USE asturias;

INSERT INTO council (council_id, name, zone) VALUES
(1, 'Allande', 'Occidente de Asturias'),
(2, 'Aller', 'Centro de Asturias'),
(3, 'Amieva', 'Oriente de Asturias'),
(4, 'Avilés', 'Centro de Asturias'),
(5, 'Belmonte de Miranda', 'Centro de Asturias'),
(6, 'Bimenes', 'Oriente de Asturias'),
(7, 'Boal', 'Occidente de Asturias'),
(8, 'Cabrales', 'Oriente de Asturias'),
(9, 'Cabranes', 'Oriente de Asturias'),
(10, 'Candamo', 'Centro de Asturias'),
(11, 'Cangas del Narcea', 'Occidente de Asturias'),
(12, 'Cangas de Onís', 'Oriente de Asturias'),
(13, 'Caravia', 'Oriente de Asturias'),
(14, 'Carreño', 'Centro de Asturias'),
(15, 'Caso', 'Centro de Asturias'),
(16, 'Castrillón', 'Centro de Asturias'),
(17, 'Castropol', 'Occidente de Asturias'),
(18, 'Coaña', 'Occidente de Asturias'),
(19, 'Colunga', 'Oriente de Asturias'),
(20, 'Corvera de Asturias', 'Centro de Asturias'),
(21, 'Cudillero', 'Occidente de Asturias'),
(22, 'Degaña', 'Occidente de Asturias'),
(23, 'Franco (El)', 'Occidente de Asturias'),
(24, 'Gijón', 'Centro de Asturias'),
(25, 'Gozón', 'Centro de Asturias'),
(26, 'Grado', 'Centro de Asturias'),
(27, 'Grandas de Salime', 'Occidente de Asturias'),
(28, 'Ibias', 'Occidente de Asturias'),
(29, 'Illano', 'Occidente de Asturias'),
(30, 'Illas', 'Centro de Asturias'),
(31, 'Langreo', 'Centro de Asturias'),
(32, 'Laviana', 'Centro de Asturias'),
(33, 'Lena', 'Centro de Asturias'),
(34, 'Valdés', 'Occidente de Asturias'),
(35, 'Llanera', 'Centro de Asturias'),
(36, 'Llanes', 'Oriente de Asturias'),
(37, 'Mieres', 'Centro de Asturias'),
(38, 'Morcín', 'Centro de Asturias'),
(39, 'Muros de Nalón', 'Centro de Asturias'),
(40, 'Nava', 'Oriente de Asturias'),
(41, 'Navia', 'Occidente de Asturias'),
(42, 'Noreña', 'Centro de Asturias'),
(43, 'Onís', 'Oriente de Asturias'),
(44, 'Oviedo', 'Centro de Asturias'),
(45, 'Parres', 'Oriente de Asturias'),
(46, 'Peñamellera Alta', 'Oriente de Asturias'),
(47, 'Peñamellera Baja', 'Oriente de Asturias'),
(48, 'Pesoz', 'Occidente de Asturias'),
(49, 'Piloña', 'Oriente de Asturias'),
(50, 'Ponga', 'Oriente de Asturias'),
(51, 'Pravia', 'Centro de Asturias'),
(52, 'Proaza', 'Centro de Asturias'),
(53, 'Quirós', 'Centro de Asturias'),
(54, 'Regueras (Las)', 'Centro de Asturias'),
(55, 'Ribadedeva', 'Oriente de Asturias'),
(56, 'Ribadesella', 'Oriente de Asturias'),
(57, 'Ribera de Arriba', 'Centro de Asturias'),
(58, 'Riosa', 'Centro de Asturias'),
(59, 'Salas', 'Occidente de Asturias'),
(60, 'San Martín del Rey Aurelio', 'Centro de Asturias'),
(61, 'San Martín de Oscos', 'Occidente de Asturias'),
(62, 'Santa Eulalia de Oscos', 'Occidente de Asturias'),
(63, 'San Tirso de Abres', 'Occidente de Asturias'),
(64, 'Santo Adriano', 'Centro de Asturias'),
(65, 'Sariego', 'Oriente de Asturias'),
(66, 'Siero', 'Centro de Asturias'),
(67, 'Sobrescobio', 'Centro de Asturias'),
(68, 'Somiedo', 'Centro de Asturias'),
(69, 'Soto del Barco', 'Centro de Asturias'),
(70, 'Tapia de Casariego', 'Occidente de Asturias'),
(71, 'Taramundi', 'Occidente de Asturias'),
(72, 'Teverga', 'Centro de Asturias'),
(73, 'Tineo', 'Occidente de Asturias'),
(74, 'Vegadeo', 'Occidente de Asturias'),
(75, 'Villanueva de Oscos', 'Occidente de Asturias'),
(76, 'Villaviciosa', 'Oriente de Asturias'),
(77, 'Villayón', 'Occidente de Asturias'),
(78, 'Yernes y Tameza', 'Centro de Asturias'),
(79, 'Valdés', 'Centro de Asturias');
