USE asturias;

INSERT INTO `asturias`.`route`
(`name`, `image`, `latitude`, `longitude`, `type`, `information`, `web`, `distance`, `time`, `origin_destination`, `council_id`)
VALUES
('El Cabril', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/v1745956418/elcabril_x8yorr.jpg', 43.06404115, -6.39256946, 'summit', 'Gracias al pastoreo de "alta montaña" Xinestosu es famoso por elaborar un excelente queso artesanal de fuerte sabor y fabricado en moldes de esparto. “El queso de la trashumancia", ya que fueron pastores castellanos y extremeños los que aportaron las pleitas, aros de esparto trenzado que servían para moldear el queso y escurrir el suero. Esta trashumancia se realizaba a través de abruptos puertos de montaña en estrechas sendas que conectaban como en ésta los valles de Somiedo y Cangas del Narcea con León.', 'https://www.turismoasturias.es/descubre/naturaleza/rutas/ascensiones/el-cabril', 14.2, '5 h. 30 min', 'Xinestosu', 11),
('Ruta de las Brañas Vaqueiras', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/v1745958313/02-branasvaqueiras_fq71a1.jpg', 43.52038427, -6.22003239, 'hiking', 'La ruta recorre varias de las antiguas brañas vaqueiras del concejo de Cudillero, algunas todavía en uso.  Atraviesa bosques autóctonos y no es inusual encontrar en su transcurso corzos, jabalíes y otros representantes de la fauna local.', 'https://www.turismoasturias.es/es/descubre/naturaleza/rutas/senderismo/ruta-de-las-branas-vaqueiras-en-cudillero', 23.9, '6 h.', 'San Martín de Luiña', 21),
('Playa de Luanco - Nieva', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/v1745958442/03-luanco_suqheq.webp', 43.62073052, 5.78724556, 'hiking', 'Se inicia esta ruta en la playa de Luanco, tomando dirección a Peroño, terraza sobre el mar. Desde este punto se contempla una inmejorable vista sobre Luanco y su puerto pesquero. En días sin calima es posible divisar La Campa Torres y al fondo los Picos de Europa. Algunas partes de la ruta se pueden hacer en bicileta.', ),
('Ruta de 7 días por el Patrimonio Industrial de Asturias', 'https://unviajecreativo.com/wp-content/uploads/2023/06/Que-ver-en-una-ruta-por-Asturias-en-7-dias-de-viaje-21.jpg', 43.54106602, -5.67217826, 'by_car', 'Una de las mejores formas de conocer y entender Asturias...', 'Ruta por algunos de los más importantes símbolos...', 'https://www.turismoasturias.es/es/que-ver-asturias-una-semana/ruta-patrimonio-industrial-asturias', 430, '7 días', 'Según el tramo', 24),
('Mieres del Camín - La Grandota (Oviedo)', 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Casa%27l_conceyu_mieres.jpg', 43.28489255, -5.76275936, 'hiking', 'Se inicia a la altura del lugar llamado Repitaneo, a unos dos kilómetros del centro urbano de Mieres, por una pista sinuosa que en fuerte subida nos conduce al Alto de El Picacho.', NULL, 'https://www.turismoasturias.es/es/descubre/naturaleza/rutas/senderismo-gr/gr105-ruta-de-las-peregrinaciones/gr105.1-mieres-la-grandota', 13, '5 h.', 'Mieres del Camín - La Grandota (Oviedo)', 37),
('Alto del Espinadal - Miera', 'ejemplo.jpg', 43.31811640, -5.46064883, 'hiking', 'Transita enteramente por una pista que discurre por la falda este de Peñamayor...', NULL, 'https://www.turismoasturias.es/descubre/naturaleza/rutas/senderismo-gr/gr105-ruta-de-las-peregrinaciones/etapa-3-alto-espinadal-puente-miera', 17, '5 h.', 'Alto del Espinadal - Miera', 40),
('La cuna de los Ferreiros', 'ejemplo.jpg', 43.25922042, -7.02052579, 'by_car', 'La frontera natural entre Asturias y Galicia es el río Eo...', 'En la margen asturiana, están Taramundi y tres concejos...', 'https://www.turismoasturias.es/es/que-ver-asturias-2-dias/cuna-ferreiros', 55, '2 días', 'Taramundi - Santa Eulalia de Oscos', 71),
('Ruta A Paicega', 'ejemplo.jpg', 43.24978054, -6.86214049, 'hiking' , 'El camino está flanqueado por muros de piedra que delimitan antiguas fincas...', NULL,  'https://www.turismoasturias.es/es/descubre/naturaleza/rutas/senderismo/ruta-de-a-paicega-pesoz', 6, '2 h. 20 min', 'Pezós/Pesoz - A Paicega', 48),
('Espinaréu - Villamayor', 'ejemplo.jpg', 43.33375572, -5.31132166, 'hiking', 'En esta etapa se ha modificado el trazado original...', NULL, 'https://www.turismoasturias.es/descubre/naturaleza/rutas/senderismo-gr/gr105-ruta-de-las-peregrinaciones/etapa-5-espinaredo-villamayor', 12, '4 h. 15 min', 'Espinaréu - Villamayor', 49),
('Villamayor - Cangas de Onís', 'ejemplo.jpg', 43.36064174, -5.21954174, 'hiking', 'Esta etapa del GR105 la podemos iniciar bien en Villamayor o bien es Sebares.', 'Discurre por los concejos de Piloña, Parres y Cangas de Onís...', 'https://www.turismoasturias.es/descubre/naturaleza/rutas/senderismo-gr/gr105-ruta-de-las-peregrinaciones/etapa-6-villamayor-cangas-de-onis', 22, '4 h.', 'Villamayor - Cangas de Onís', 49),
('El Mechero de Saús', 'ejemplo.jpg', 43.29089783, -5.65371752, 'mountain_bike', 'La ruta pasa por los concejos de Langreo y Mieres...', 'Discurre por sendas verdes, carreteras locales con poco tráfico...', 'https://www.turismoasturias.es/descubre/naturaleza/rutas/rutas-en-btt/el-mechero-de-saus', 37, '1 día', 'El Entrego - Ablaña', 60),
('Ruta Carlos V', 'ejemplo.jpg', 43.54542113, -5.39981989, 'hiking', 'Hace cinco siglos, la llegada a España de Carlos V tuvo lugar en Tazones...', 'Esta ruta une historia, etnografía y naturaleza...', 'https://www.turismoasturias.es/es/descubre/naturaleza/rutas/senderismo/ruta-carlos-v', 11, '2 h. 50 min', 'Tazones - Villaviciosa', 76),
('Ruta de los Lagos', 'ejemplo.jpg', 43.05868933, -6.15003218, 'hiking', 'Iniciamos la ruta en el Alto de la Farrapona...', NULL, 'https://www.turismoasturias.es/es/descubre/naturaleza/rutas/senderismo/ruta-de-los-lagos-de-saliencia', 14, '5 h. 30 min', 'Alto de la Farrapona', 68);
