USE asturias;

INSERT INTO `asturias`.`route`
(`name`, `image`, `latitude`, `longitude`, `information`, `comments`, `track`, `distance`, `time`, `origin_destination`, `council_id`)
VALUES
('Ruta de 7 días por el Patrimonio Industrial de Asturias', 'https://unviajecreativo.com/wp-content/uploads/2023/06/Que-ver-en-una-ruta-por-Asturias-en-7-dias-de-viaje-21.jpg', 43.54106602, -5.67217826, 'Una de las mejores formas de conocer y entender Asturias...', 'Ruta por algunos de los más importantes símbolos...', 'https://www.turismoasturias.es/es/que-ver-asturias-una-semana/ruta-patrimonio-industrial-asturias', 430, '7 días', 'Según el tramo', 24),
('Mieres del Camín - La Grandota (Oviedo)', 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Casa%27l_conceyu_mieres.jpg', 43.28489255, -5.76275936, NULL, NULL, 'https://www.turismoasturias.es/es/descubre/naturaleza/rutas/senderismo-gr/gr105-ruta-de-las-peregrinaciones/gr105.1-mieres-la-grandota', 13, '5 h.', 'Mieres del Camín - La Grandota (Oviedo)', 37),
('Alto del Espinadal - Miera', 'ejemplo.jpg', 43.31811640, -5.46064883, 'Transita enteramente por una pista que discurre por la falda este de Peñamayor...', NULL, 'https://www.turismoasturias.es/descubre/naturaleza/rutas/senderismo-gr/gr105-ruta-de-las-peregrinaciones/etapa-3-alto-espinadal-puente-miera', 17, '5 h.', 'Alto del Espinadal - Miera', 40),
('La cuna de los Ferreiros', 'ejemplo.jpg', 43.25922042, -7.02052579, 'La frontera natural entre Asturias y Galicia es el río Eo...', 'En la margen asturiana, están Taramundi y tres concejos...', 'https://www.turismoasturias.es/es/que-ver-asturias-2-dias/cuna-ferreiros', 55, '2 días', 'Taramundi - Santa Eulalia de Oscos', 71),
('Ruta A Paicega', 'ejemplo.jpg', 43.24978054, -6.86214049, NULL, 'El camino está flanqueado por muros de piedra que delimitan antiguas fincas...', 'https://www.turismoasturias.es/es/descubre/naturaleza/rutas/senderismo/ruta-de-a-paicega-pesoz', 6, '2 h. 20 min', 'Pezós/Pesoz - A Paicega', 48),
('Espinaréu - Villamayor', 'ejemplo.jpg', 43.33375572, -5.31132166, 'En esta etapa se ha modificado el trazado original...', NULL, 'https://www.turismoasturias.es/descubre/naturaleza/rutas/senderismo-gr/gr105-ruta-de-las-peregrinaciones/etapa-5-espinaredo-villamayor', 12, '4 h. 15 min', 'Espinaréu - Villamayor', 49),
('Villamayor - Cangas de Onís', 'ejemplo.jpg', 43.36064174, -5.21954174, 'Esta etapa del GR105 la podemos iniciar bien en Villamayor o bien es Sebares.', 'Discurre por los concejos de Piloña, Parres y Cangas de Onís...', 'https://www.turismoasturias.es/descubre/naturaleza/rutas/senderismo-gr/gr105-ruta-de-las-peregrinaciones/etapa-6-villamayor-cangas-de-onis', 22, '4 h.', 'Villamayor - Cangas de Onís', 49),
('El Mechero de Saús', 'ejemplo.jpg', 43.29089783, -5.65371752, 'La ruta pasa por los concejos de Langreo y Mieres...', 'Discurre por sendas verdes, carreteras locales con poco tráfico...', 'https://www.turismoasturias.es/descubre/naturaleza/rutas/rutas-en-btt/el-mechero-de-saus', 37, '1 día', 'El Entrego - Ablaña', 60),
('Ruta Carlos V', 'ejemplo.jpg', 43.54542113, -5.39981989, 'Hace cinco siglos, la llegada a España de Carlos V tuvo lugar en Tazones...', 'Esta ruta une historia, etnografía y naturaleza...', 'https://www.turismoasturias.es/es/descubre/naturaleza/rutas/senderismo/ruta-carlos-v', 11, '2 h. 50 min', 'Tazones - Villaviciosa', 76),
('Ruta de los Lagos', 'ejemplo.jpg', 43.05868933, -6.15003218, 'Iniciamos la ruta en el Alto de la Farrapona...', NULL, 'https://www.turismoasturias.es/es/descubre/naturaleza/rutas/senderismo/ruta-de-los-lagos-de-saliencia', 14, '5 h. 30 min', 'Alto de la Farrapona', 68);
