USE asturias;

INSERT INTO preroman_art (name, image, latitude, longitude, unesco_heritage, information, web, address, council_id)
VALUES
('Iglesia de San Tirso el Real', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746741480/San_Tirso_de_Oviedo_1_zek2xt.jpg', 43.362194, -5.843767, 0, 'Fundada en el siglo IX, sufrió sucesivas remodelaciones en los siglos XII, XVI, XVIII y XX.', NULL, 'Pza. de Alfonso II. 33003 Oviedo', 44),
('Iglesia de San Salvador de Priesca', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746741532/San_Salvador_de_Priesca_u6z3gt.jpg', 43.484586,-5.360632, 0, 'Iglesia prerrománica, erigida en el año 921, según varios epígrafes grabados en el revoco de sus pilastras y desaparecidos hacia el año 1922.', NULL, 'Aldea la Quintana, 7. 33316 Priesca', 76),
('Santa Cristina de Lena', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746741606/IMG20230412172739_hfxl1j.jpg', 43.128594,-5.813222, 1, 'Situada sobre una colina que domina el valle del río Lena, está sin duda relacionada con las obras del Naranco, aunque detecta mayor tosquedad ornamental.', NULL, 'La Vega del Rei. 33630 Lena', 33),
('San Andrés de Bedriñana', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746741689/bredinana_agegj8.jpg', 43.500562,-5.438335, 0, 'Conserva restos de la ermita primitiva.', NULL, 'Lugar La Pola, 9. 33315 Bedriñana', 76),
('Santa María del Naranco', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746741838/santa-maria-naranco_s3qxve.jpg', 43.379055, -5.865849, 1, 'El Palacio de Ramiro I ubicado en la falda del monte Naranco es una singular construcción sin una finalidad esclarecida. El edificio, de planta rectangular, está dividido en dos pisos, uno inferior o cripta que es totalmente cerrada y una superior diáfana, unidas por una escalera exterior.', 'https://www.santamariadelnaranco.es/', 'Avda de los Monumentos (Monte Naranco), Oviedo', 44), 
('Cámara Santa', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746742102/cripta-de-santa-leocadia-catedral-de-oviedo_exsywk.webp', 43.362488, -5.843598, 1, 'Fundada como capilla palatina por un rey asturiano, Alfonso II el Casto, la Cámara Santa de la Catedral de El Salvador de Oviedo ha sido testigo activo de miles de historias y avatares: punto de encuentro de peregrinos, devotos, viajeros, aventureros y hasta revolucionarios.', 'https://catedraldeoviedo.com/conoce-cada-rincon/camara-santa/', '', 44), 
('La Foncalada', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746742328/img-20180328-195325980_e83s00.jpg', 43.365280, -5.846036, 1, 'Data del siglo IX y fue construida durante el reinado de Alfonso III el Magno. Constituye el único ejemplo de construcción de carácter civil con fines de utilidad pública de la Alta Edad Media. Protege el alumbramiento de un manantial de agua potable que brota del mismo suelo.', NULL, 'C/ Foncalada (esquina C/ Gascona), Oviedo', 44), 
('San Miguel de Lillo', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746742545/san-miguel-1_ij8vwe.jpg', 43.380314, -5.868406, 1, 'El edificio que hoy contemplamos corresponde a un tercio aproximadamente de la edificación primitiva. Durante la baja Edad Media, la iglesia se derrumbó en parte, reconstruyéndose entonces la cabecera actual. Hoy está en pie el primitivo pórtico y uno de los tramos de la nave original.', 'https://www.santamariadelnaranco.es/', 'Avda de los Monumentos (Monte Naranco), Oviedo', 44), 
('Iglesia de Santiago de Gobiendes', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746742734/gobiendes_jaethl.jpg', 43.46928, -5.232562, 0, 'Construida en el siglo X y reedificada parcialmente en el siglo XIX, esta iglesia prerrománica cuenta con planta basilical, está dividida en tres naves y tiene cabecera tripartita. A los pies de la nave, se conservan dos compartimentos del pórtico primitivo.', 'https://sierradelsueve.es/?page_id=605', NULL, 19), 
('Iglesia de San Julián de los Prados', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746742952/iglesia_san_julian_prados_s_495516418_h7dnsb.avif', 43.367712, -5.837325, 1, 'La iglesia prerrománica de San Julián de los Prados es el más antiguo y mayor de los edificios prerrománicos que aún se conservan. Construida durante el reinado de Alfonso II el Casto, fue dedicada a San Julián y su esposa Santa Basilisa. En el año 896 fue donada a la catedral de San Salvador.', 'https://www.sanjuliandelosprados.com/', 'Selgas, 2 Oviedo', 44), 
('Iglesia de Santo Adriano de Tuñón', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746743300/unnamed_hbdj2y.jpg', 43.291615, -5.981285, 0, 'La iglesia de Santo Adriano fue fundada por el rey Alfonso III. Tiene planta rectangular, con tres naves separadas por arquerías de medio punto sobre pilares cuadrangulares de piedra, cubierta de madera a dos aguas y cabecera rectangular triple con bóvedas de cañón.', 'https://www.santoadriano.org/iglesia-prerromanica-de-tunon', NULL, 64), 
('Santianes de Pravia', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746743630/Santianes_de_Pravia_-_04_ayo8p4.jpg', 43.501959, -6.099163, 0, 'Es la más antigua de las iglesias Prerrománicas de Asturias y fue mandada construir por los reyes Silo y Adosinda, que trasladaron a Pravia la capital del Reino Astur. De la basílica primitiva sólo quedan algunos restos en la nave central y en los muros laterales.', 'https://praviaturismo.es/', NULL, 51), 
('Iglesia de Santa María de Bendones', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746743930/Frontal_Santa_Mari%CC%81a_de_Bendones_qbaex7.jpg', 43.3362, -5.806374, 0, 'Iglesia prerrománica edificada, probablemente, en tiempos del monarca Alfonso II. Destruida en 1936, fue sometida a una polémica reconstrucción en 1958. El templo actual presenta una nave central única, cabecera tripartita y nártex a los pies.', NULL, NULL, 44), 
('Iglesia de San Pedro de Nora', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746744079/San_Pedro_de_Nora1_mrb1jx.jpg', 43.36908, -5.962004, 0, 'La referencia documental más antigua es el 20 de enero del año 905. Su estructura es la misma que la de Santullano a pesar de tener algunos rasgos diferentes. La planta es basilical, con tres naves separadas por pilares, cabecera rectangular tripartita orientada al este y un pórtico al oeste.', NULL, NULL, 54), 
('Iglesia de San Salvador de Valdediós', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746744268/valdedios-02_kxmzso.jpg', 43.436857, -5.506621, 0, 'Fue consagrada en el 893 por siete obispos, según reza la lápida que se conserva en la capilla lateral sur. Se estructura en planta basilical de tres naves, cabecera tripartita con capillas de pequeñas dimensiones, y dos compartimentos adosados a los muros norte y sur que hacen de falso crucero.', 'https://monasteriovaldedios.com/', NULL, 76);