USE asturias;

INSERT INTO rock_art (name, image, latitude, longitude, period, information, web, council_id)
VALUES
('Cueva de Covaciella', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746736822/Imagen1-1-1773495033_poupm3.jpg', 43.318232,-4.875262, 'Magdaleniense', 'Cueva con pinturas de bisontes, caballos, ciervos... de más de 14.000 años.', 'https://artepaleoliticoenasturias.com/investigacion-y-paraiso-rupestre/la-covaciella', 8),
('Cueva del Demo', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746737112/foto_659_qm8ytm.jpg', 43.38293,-6.850428, 'Bronce antiguo', 'Cueva en las proximidades de Froseira en el concejo de Boal.', NULL, 7),
('Cueva de Llonín', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746737194/llonin_panel_princiapl_ww0tuu.jpg', 43.330556,-4.645278, 'Desde el Gravetiense hasta el Magdaleniense.', 'Descubierta por los productores de queso cabrales, la cueva alberga más de un centenar de figuras representadas.', NULL, 46),
('Cueva del Conde o del Fornu', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746737265/cueva_conde_v0wark.jpg', 43.298253,-5.986963, 'Paleolítico superior', 'Un abrigo rocoso con algunas de las más antiguas manifestaciones artísticas de la humanidad.','https://laponte.org/', 64),
('Cueva y Aula Didáctica de la Loja', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746737368/la_loja_lpvzi9.webp', 43.331435, -4.559488, 'Paleolítico', 'Fue la primera cueva con arte paleolítico descubierta en Asturias. El Aula Didáctica de La Loja gira sobre el arte rupestre presente en la cueva y las riquezas prehistóricas de la zona. La visita al Aula se realiza con un guía, y después, se lleva a cabo la visita a la Cueva de La Loja.', 'https://www.aytopbpanes.es/cueva-de-la-loja', 47), 
('Cueva de La Peña o de Candamo', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746737822/cueva-candamo_xx32a1.jpg', 43.4562, -6.07266, 'Solutrense y Magdaleniense', 'Destacan en él el Muro de los Grabados, por contar con el mayor número de imágenes y la organización más compleja con superposiciones, y el Camarín, una oquedad elevada con representaciones de caballos y bóvidos, dispuestas para ser vistas desde la propia sala.', 'https://candamoturismo.es/la-cueva/', 10), 
('Cueva de El Buxu', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746738148/buxu_ejuoch.jpg', 43.357730, -5.099614, 'Solutrense y Magdaleniense', 'Un lugar donde admirar grabados de caballos, cabras, ciervos y bisontes, y figuras geométricas y zoomórficas. Destaca la rara escultura de un ave tallada sobre el colmillo de un oso de las cavernas y una plaqueta de piedra caliza grabada con diferentes motivos (animales, signos y antropomorfos).', 'https://yacimientos.asturias.es/cueva-del-buxu', 12), 
('Cueva de Tito Bustillo', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746738461/tito_bustillo_mtpozs.jpg', 43.4607, -5.06735, 'Magdaleniense', 'Una galería de unos 700 metros de longitud, a la que se abren estancias anexas. 11 conjuntos que reúnen más de cien representaciones grabadas y pintadas que se corresponden con dos fases, una premagdaleniense (signos en rojo y escasa figuración animal) y otra magdaleniense, con distintas técnicas.', 'https://www.centrotitobustillo.com/es/', 56), 
('Abrigo de Santo Adriano', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746738795/Abrigo_de_Santo_Adriano_002_n4t6zd.jpg', 43.298580, -5.987977, 'Paleolítico superior', 'Compuesto principalmente bisontes, ciervas y cabras que en total suman unas 30 figuras. También contiene algunos signos aspados. Pertenece a un conjunto de lugares denominados "santuarios exteriores" por su ubicación en los vestíbulos de las cuevas o en abrigos donde llega la luz solar.', 'https://laponte.org/', 64), 
('Cueva de los Azules', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746739097/azules_rbzqhh.jpg', 43.359864, -5.131429, 'Periodo Aziliense (Epipaleolítico)', 'Alberga niveles fértiles magdalenienses. Es conocida por sus registros epipaleolíticos, de la cultura Aziliense, de la que se ha convertido en yacimiento tipo de todo el área cantábrica. La recreación del enterramiento de Los Azules puede ser visitada en el Museo Arqueológico de Asturias.', 'https://www.turismoasturias.es/es/descubre/cultura/arte-rupestre/rupestre-cueva-de-los-azules', 12), 
('Cueva de El Pindal', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746739410/el_pindal_02_a2da0j.jpg', 43.397267, -4.532719, 'Magdaleniense', 'Una única entrada sobre el mar y una galería longitudinal de unos 600 metros de la que sólo se visitan los primeros 300. Distribuido en cinco zonas, el conjunto magdaleniense alberga representaciones zoomorfas como cérvidos, caballos, bisontes, y destacan un pez y un mamut.', 'https://yacimientos.asturias.es/cueva-del-pindal', 55), 
('Abrigos de Fresnedo', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746739684/abrigos_detalle_sql8ov.jpg', 43.123477, -6.054853, 'Edad de bronce', 'Sobre el desfiladero de La Estrechura, consiste la estación prehistórica en cinco covachas, conteniendo diferentes representaciones pictóricas del llamado ''arte esquemático'' y atribuíbles a la Edad del Bronce. Son frecuentes las representaciones, muy sumarias de cabras.', 'https://www.turismoasturias.es/es/descubre/cultura/arte-rupestre/rupestre-abrigos-de-fresnedo', 72), 
('La Cuevona de Ardines', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746739950/cuevona_ardines_agc5jz.jpg', 43.4607, -5.06735, 'Solutrense y Magdaleniense', 'Destaca por el tamaño considerable de su sala principal, donde el techo alcanza los 40 metros de altura, hoy perforado por un boquete natural que permite el paso de la luz diurna. Las visitas que se realizan a la Cuevona de Ardines son de interés geológico.', 'https://www.centrotitobustillo.com/es/visita-la-cuevona-de-ardines', 56), 
('Cueva de La Lluera', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746740317/entrada-cavidad-cueva-lluera_omrngc.jpg', 43.334687, -5.933297, 'Solutrense', 'Su extraordinaria importancia se debe al magnífico conjunto de grabados que guardan las dos oquedades. En la primera de ellas el contenido principal son grabados que representan en su mayoría animales. Podemos descubrir en sus muros caballos, uros, ciervos y bisontes entre otros.', 'https://artepaleoliticoenasturias.com/cuevas-visitables/la-cuenca-del-nalon/la-lluera/', 44), 
('Cueva del Molín o Abrigo de Entrefoces', 'https://res.cloudinary.com/dpz1cfyyy/image/upload/w_800,q_auto/v1746740678/abrigoentrefoces1_gmdwxq.jpg', 43.257163, -5.871210, 'Paleolítico superior', 'De las cuevas del concejo de Morcín, el Abrigo de Entrefoces puede que sea la más llamativa. Conserva esta cueva un panel con la representación de dos ciervas y un caballo, grabados en época magdaleniense.', 'https://artepaleoliticoenasturias.com/investigacion-y-paraiso-rupestre/el-molin/', 38);