-- MySQL Script generated by MySQL Workbench
-- Thu Apr 17 09:25:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema asturias
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `asturias` ;

-- -----------------------------------------------------
-- Schema asturias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asturias` DEFAULT CHARACTER SET utf8 ;
USE `asturias` ;

-- -----------------------------------------------------
-- Table `asturias`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`table1` ;

CREATE TABLE IF NOT EXISTS `asturias`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`councils`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`councils` ;

CREATE TABLE IF NOT EXISTS `asturias`.`councils` (
  `council_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `zone` VARCHAR(45) NULL,
  PRIMARY KEY (`council_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`motorhome_areas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`motorhome_areas` ;

CREATE TABLE IF NOT EXISTS `asturias`.`motorhome_areas` (
  `areas_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `image` VARCHAR(128) NOT NULL,
  `coordinates` POINT NOT NULL,
  `drinking_water` TINYINT UNSIGNED NOT NULL,
  `waste_water` TINYINT UNSIGNED NOT NULL,
  `black_water` TINYINT UNSIGNED NOT NULL,
  `places` INT UNSIGNED NULL,
  `access` VARCHAR(255) NULL,
  `type` ENUM("publica", "privada") NOT NULL DEFAULT 'pública',
  `max_stay` VARCHAR(45) NULL,
  `address` VARCHAR(128) NOT NULL,
  `council_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`areas_id`),
  UNIQUE INDEX `nombre_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `coordenadas_UNIQUE` (`coordinates` ASC) VISIBLE,
  INDEX `fk_areas_autocaravanas_concejos_idx` (`council_id` ASC) VISIBLE,
  CONSTRAINT `fk_areas_autocaravanas_concejos`
    FOREIGN KEY (`council_id`)
    REFERENCES `asturias`.`councils` (`council_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`routes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`routes` ;

CREATE TABLE IF NOT EXISTS `asturias`.`routes` (
  `route_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `image` VARCHAR(128) NOT NULL,
  `information` VARCHAR(300) NOT NULL,
  `comments` VARCHAR(300) NULL,
  `track` VARCHAR(128) NULL,
  `distance` INT UNSIGNED NOT NULL,
  `coordinates` POINT NOT NULL,
  `time` VARCHAR(45) NULL,
  `origin_destination` VARCHAR(128) NULL,
  `council_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`route_id`),
  INDEX `fk_rutas_concejos1_idx` (`council_id` ASC) VISIBLE,
  CONSTRAINT `fk_rutas_concejos1`
    FOREIGN KEY (`council_id`)
    REFERENCES `asturias`.`councils` (`council_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`preroman_art`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`preroman_art` ;

CREATE TABLE IF NOT EXISTS `asturias`.`preroman_art` (
  `preroman_art_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `image` VARCHAR(128) NOT NULL,
  `unesco_heritage` TINYINT NOT NULL,
  `information` VARCHAR(300) NULL,
  `web` VARCHAR(128) NULL,
  `coordinates` POINT NOT NULL,
  `address` VARCHAR(128) NULL,
  `council_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`preroman_art_id`),
  INDEX `fk_arte_prerromanico_concejos1_idx` (`council_id` ASC) VISIBLE,
  CONSTRAINT `fk_arte_prerromanico_concejos1`
    FOREIGN KEY (`council_id`)
    REFERENCES `asturias`.`councils` (`council_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`beachs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`beachs` ;

CREATE TABLE IF NOT EXISTS `asturias`.`beachs` (
  `beach_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `image` VARCHAR(128) NOT NULL,
  `information` VARCHAR(300) NOT NULL,
  `coordinates` POINT NOT NULL,
  `services` VARCHAR(255) NOT NULL,
  `beach_type` VARCHAR(128) NOT NULL,
  `council_id` INT NOT NULL,
  PRIMARY KEY (`beach_id`),
  INDEX `fk_playas_concejos1_idx` (`council_id` ASC) VISIBLE,
  CONSTRAINT `fk_playas_concejos1`
    FOREIGN KEY (`council_id`)
    REFERENCES `asturias`.`councils` (`council_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`rock_art`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`rock_art` ;

CREATE TABLE IF NOT EXISTS `asturias`.`rock_art` (
  `rock_art_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `image` VARCHAR(128) NOT NULL,
  `period` VARCHAR(45) NOT NULL,
  `information` VARCHAR(300) NOT NULL,
  `web` VARCHAR(128) NULL,
  `coordinates` POINT NOT NULL,
  `council_id` INT NOT NULL,
  PRIMARY KEY (`rock_art_id`),
  INDEX `fk_arte_rupestre_concejos1_idx` (`council_id` ASC) VISIBLE,
  CONSTRAINT `fk_arte_rupestre_concejos1`
    FOREIGN KEY (`council_id`)
    REFERENCES `asturias`.`councils` (`council_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`museum_cultural_centers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`museum_cultural_centers` ;

CREATE TABLE IF NOT EXISTS `asturias`.`museum_cultural_centers` (
  `museum_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `image` VARCHAR(128) NOT NULL,
  `web` VARCHAR(128) NULL,
  `information` VARCHAR(300) NOT NULL,
  `coodinates` POINT NOT NULL,
  `free` TINYINT NOT NULL,
  `council_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`museum_id`),
  INDEX `fk_museos_espacios_culturales_concejos1_idx` (`council_id` ASC) VISIBLE,
  CONSTRAINT `fk_museos_espacios_culturales_concejos1`
    FOREIGN KEY (`council_id`)
    REFERENCES `asturias`.`councils` (`council_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`users` ;

CREATE TABLE IF NOT EXISTS `asturias`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password_hash` VARCHAR(80) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`favourites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`favourites` ;

CREATE TABLE IF NOT EXISTS `asturias`.`favourites` (
  `favourite_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` ENUM('area', 'route', 'beach') NOT NULL,
  `point_id` INT UNSIGNED NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`favourite_id`),
  INDEX `fk_favourites_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_favourites_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `asturias`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asturias`.`visited`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asturias`.`visited` ;

CREATE TABLE IF NOT EXISTS `asturias`.`visited` (
  `visited_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` ENUM('area', 'route', 'preroman_art', 'beach', 'museum', 'rock_art') NOT NULL,
  `point_id` INT UNSIGNED NOT NULL,
  `comments` VARCHAR(400) NULL,
  `visit_date` DATE NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`visited_id`),
  INDEX `fk_visited_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_visited_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `asturias`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
